# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://bit97.github.io/
baseurl: /
title: Federico Bitondo
author: Federico Bitondo
description: Personal blog and resume
avatar: profile.jpeg
email: federico.bitondo@gmail.com
github: bit97


# needed for travis-ci build
exclude: [vendor]
